# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='validity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Valid'), (2, 'Invalid'), (3, 'Sold'), (4, 'Unsold')], default=1),
            preserve_default=False,
        ),
    ]
