# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20190319_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='bids.Bid'),
        ),
    ]
