# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20190325_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.User'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='bids.Bid'),
        ),
    ]
