# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20190325_1453'),
        ('bids', '0004_auto_20190323_0938'),
    ]

    operations = [
    ]
