# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_merge_20190326_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='charge_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='payment_token',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='bid',
            name='validity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Valid'), (2, 'Invalid'), (3, 'Sold'), (4, 'Unsold'), (5, 'Pending')], default=5),
        ),
    ]
