# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_auto_20190328_1908'),
        ('bids', '0005_auto_20190326_1849'),
    ]

    operations = [
    ]
