# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_merge_20190329_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='payment_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
