# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190312_1153'),
        ('groups', '0002_auto_20190311_1230'),
    ]

    operations = [
    ]
