# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 11:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190305_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHERS')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits.', regex='^[1-9]{1}\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buyer'), (2, 'Seller'), (3, 'Both')], default=3),
        ),
    ]
