# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190313_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'MALE', 'MALE'), (b'FEMALE', 'FEMALE'), (b'OTHERS', 'OTHERS')], max_length=8, null=True),
        ),
    ]
