CONSTANTS = {
    "TEXT_SIZE_SMALL": 32,
    "TEXT_SIZE_MEDIUM": 64,
    "TEXT_SIZE_LARGE": 128,
    "INITIAL_BALANCE": 0,
    "PASSWORD_MIN_LENGTH": 6,
    "PASSWORD_MAX_LENGTH": 32,
    "FIRST_NAME_MIN_LENGTH": 2,
    "FIRST_NAME_MAX_LENGTH": 32,
    "LAST_NAME_MAX_LENGTH": 32,
}
