GLOBAL_CONSTANTS = {
    "TEXT_SIZE_SMALL": 32,
    "TEXT_SIZE_MEDIUM": 128,
    "TEXT_SIZE_LARGE": 512,
    "TEXT_SIZE_DETAIL": 5000,
}


USER_CONSTANTS = {
    "INITIAL_BALANCE": 0,
    "PASSWORD_MIN_LENGTH": 6,
    "PASSWORD_MAX_LENGTH": 128,
    "FIRST_NAME_MIN_LENGTH": 2,
    "FIRST_NAME_MAX_LENGTH": 32,
    "LAST_NAME_MAX_LENGTH": 32,
    
    "PASSWORD_RESET_CONFIRM_URL": "http://localhost:3000/reset_password/confirm",
    
    "M": 'MALE',
    "F": 'FEMALE',
    "O": 'OTHERS',
    "PHONE_NUMBER": 10,
    "GENDER": 8,
}
