# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='short_desc',
            new_name='short_description',
        ),
    ]
