# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190305_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='months_old',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='more_info',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_required',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
