# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20190305_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'sold'), (4, 'unsold')], default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='more_info',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
    ]
