# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190305_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'onhold'), (3, 'sold'), (4, 'unsold')], default=1),
        ),
    ]
