# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20190325_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'onhold'), (4, 'sold'), (5, 'unsold')], default=1),
        ),
    ]
