# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190326_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_bid_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
