# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 15:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190327_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='charge_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'onhold'), (4, 'sold'), (5, 'unsold'), (6, 'payment_pending')], default=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
