# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190327_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='payment_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
