# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190328_1154'),
        ('items', '0008_item_min_bid_price'),
    ]

    operations = [
    ]
