# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_merge_20190329_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'onhold'), (4, 'sold'), (5, 'unsold'), (6, 'payment_pending')], default=6),
        ),
    ]
