# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 08:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20190330_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='payment_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
