GLOBAL_CONSTANTS = {
    "TEXT_SIZE_SMALL": 32,
    "TEXT_SIZE_MEDIUM": 512,
    "TEXT_SIZE_LARGE": 1024,
    "TEXT_SIZE_DETAIL": 5000,
}


USER_CONSTANTS = {
    "INITIAL_BALANCE": 0,
    "PASSWORD_MIN_LENGTH": 6,
    "PASSWORD_MAX_LENGTH": 32,
    "FIRST_NAME_MIN_LENGTH": 2,
    "FIRST_NAME_MAX_LENGTH": 32,
    "LAST_NAME_MAX_LENGTH": 32,
}
